#!/usr/bin/env python3
"""Summarize benchmark-question-formats.ts JSON; no external dependencies.

Usage: python3 scripts/analyze-question-formats.py [--markdown] FILE [FILE ...]
CIs resample paired rounds, not individual concurrent batches. A separate
fixture-cluster CI resamples per-fixture mean differences (small fixture sets).
These measure this workload/run, not general prompt-quality uncertainty.
"""
import json
import random
import statistics as st
import sys


def interval(values):
    rng = random.Random(20260929)
    means = sorted(st.mean(rng.choices(values, k=len(values))) for _ in range(10000))
    return [round(means[249], 2), round(means[9749], 2)]


def analyze(path):
    with open(path) as file:
        report = json.load(file)
    if not report.get("finishedAt"):
        raise ValueError(f"Incomplete run: {path}")
    samples = [s for s in report["samples"] if not s["warmup"]]
    baselines = {s["round"]: s for s in samples if s["format"] == "baseline"}
    output = {"path": path, "callsIncludingWarmups": sum(len(s["batches"]) for s in report["samples"]),
              "costIncludingWarmups": sum(b.get("usage", {}).get("cost", 0) for s in report["samples"] for b in s["batches"]),
              "formats": []}
    for fmt in report["formats"]:
        rows = [s for s in samples if s["format"] == fmt]
        deltas = [s["elapsedMs"] - baselines[s["round"]]["elapsedMs"] for s in rows]
        cluster_deltas = [st.mean(s["elapsedMs"] - baselines[s["round"]]["elapsedMs"] for s in rows if s["fixture"] == f["id"]) for f in report["fixtures"] if any(s["fixture"] == f["id"] for s in rows)]
        score_deltas, crossings, jaccards = [], [], []
        for row in rows:
            baseline = baselines[row["round"]]
            bscores = {s["name"]: s["score"] for b in baseline["batches"] for s in b["scores"]}
            scores = {s["name"]: s["score"] for b in row["batches"] for s in b["scores"]}
            score_deltas.extend(abs(scores[n] - bscores[n]) for n in scores)
            crossings.extend((scores[n] >= report["threshold"]) != (bscores[n] >= report["threshold"]) for n in scores)
            a, b = set(row["selected"]), set(baseline["selected"])
            jaccards.append(len(a & b) / len(a | b) if a | b else 1)
        out = next(dict(s) for s in report["summary"] if s["format"] == fmt)
        out.update({"pairedRoundMeanDelta95CI": interval(deltas), "pairedFixtureMeanDelta95CI": interval(cluster_deltas),
                    "fasterFraction": st.mean(d < 0 for d in deltas), "meanSelectedJaccard": st.mean(jaccards),
                    "meanAbsoluteScoreDelta": st.mean(score_deltas), "thresholdCrossingFraction": st.mean(crossings),
                    "requiredChecks": sum(len(f["required"]) for s in rows for f in report["fixtures"] if f["id"] == s["fixture"]),
                    "forbiddenChecks": sum(len(f["forbidden"]) for s in rows for f in report["fixtures"] if f["id"] == s["fixture"])})
        output["formats"].append(out)
    return output


def markdown(reports):
    print("# Question-format benchmark: generated results\n")
    print("Generated by `scripts/analyze-question-formats.py --markdown`. Latencies are client wall time, including HTTP and response parsing; warmups are excluded from tables. Costs and call totals include warmups.\n")
    for report in reports:
        print(f"## `{report['path'].rsplit('/', 1)[-1]}`\n")
        print(f"{report['callsIncludingWarmups']} HTTP calls; reported cost ${report['costIncludingWarmups']:.6f}.\n")
        print("| Format | n | Mean ms | Median ms | p95 ms | Input tokens | Output tokens | Bytes | Mean latency change | Input change |")
        print("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")
        baseline = next(s for s in report['formats'] if s['format'] == 'baseline')
        for s in report['formats']:
            print(f"| {s['format']} | {s['n']} | {s['meanMs']:.1f} | {s['medianMs']:.1f} | {s['p95Ms']:.1f} | {s['meanInputTokens']:.1f} | {s['meanOutputTokens']:.1f} | {s['meanRequestBytes']:.0f} | {100*(s['meanMs']/baseline['meanMs']-1):+.1f}% | {100*(s['meanInputTokens']/baseline['meanInputTokens']-1):+.1f}% |")
        print("\nPaired latency deltas below are variant minus baseline (negative = faster). 95% percentile bootstrap CIs use 10,000 seeded resamples. Fixture CI resamples fixture mean deltas, not all individual requests.\n")
        print("| Format | Mean delta ms | Round CI ms | Fixture CI ms | Faster pairs | Exact top-6 agreement | Mean Jaccard | Score threshold crossings | Required misses/checks | Forbidden hits/checks |")
        print("|---|---:|---|---|---:|---:|---:|---:|---:|---:|")
        for s in report['formats']:
            print(f"| {s['format']} | {s['pairedMeanDeltaMs']:.1f} | {s['pairedRoundMeanDelta95CI']} | {s['pairedFixtureMeanDelta95CI']} | {100*s['fasterFraction']:.1f}% | {100*s['selectionAgreement']:.1f}% | {s['meanSelectedJaccard']:.3f} | {100*s['thresholdCrossingFraction']:.1f}% | {s['requiredMisses']}/{s['requiredChecks']} | {s['forbiddenHits']}/{s['forbiddenChecks']} |")
        print("\nBaseline agreement is 100% by definition, **not accuracy**. Required/forbidden checks are partial hand labels, not exhaustive gold sets; `0/0` means unlabelled, not perfect. Token/byte counts are per full selection, summed across batches.\n")
    print(f"Total: {sum(r['callsIncludingWarmups'] for r in reports)} HTTP calls; reported cost ${sum(r['costIncludingWarmups'] for r in reports):.6f}.")


if __name__ == "__main__":
    paths = sys.argv[1:]
    as_markdown = '--markdown' in paths
    if as_markdown:
        paths.remove('--markdown')
    if not paths:
        raise SystemExit(__doc__)
    reports = [analyze(path) for path in paths]
    if as_markdown:
        markdown(reports)
    else:
        print(json.dumps(reports, indent=2))
